[ req ]

default_bits        = 2048
default_keyfile     = server-key.pem
distinguished_name  = subject
req_extensions      = req_ext
x509_extensions     = x509_ext
string_mask         = utf8only

[ subject ]

countryName                 = Country Name (2 letter code)
countryName_default         = PE

stateOrProvinceName         = State or Province Name (full name)
stateOrProvinceName_default = Lima

localityName                = Locality Name (eg, city)
localityName_default        = Lima

organizationName            = Organization Name (eg, company)
organizationName_default    = Soluciones System, PE

commonName                  = Common Name (e.g. server FQDN or YOUR name)
commonName_default          = woocomerce-api.local

emailAddress                = Email Address
emailAddress_default        = admin@woocomerce-api.local

[ dn ]
C  = PE
ST = Lima
L  = Lima
O  = Soluciones System
OU = Development Team
CN = woocomerce-api.local

[ x509_ext ]

subjectKeyIdentifier   = hash
authorityKeyIdentifier = keyid,issuer

basicConstraints       = CA:FALSE
keyUsage               = digitalSignature, keyEncipherment
subjectAltName         = @alternate_names
nsComment              = "OpenSSL Generated Certificate for Development"

[ req_ext ]

subjectKeyIdentifier = hash

basicConstraints     = CA:FALSE
keyUsage             = digitalSignature, keyEncipherment
subjectAltName       = @alternate_names
nsComment            = "OpenSSL Generated Certificate for Development"

[ alternate_names ]

DNS.1 = woocomerce-api.local
DNS.2 = www.woocomerce-api.local
DNS.3 = *.woocomerce-api.local

