# /usr/local/lsws/conf/vhosts/html/vhconf.conf
#
# PLAIN TEXT CONFIGURATION FILE
# author: cesar auris
# version: 1.0.2
#

docRoot /var/www/html/public_html
enableGzip 1
enableIpGeo 1

errorlog /var/www/html/logs/error.log {
  useServer               0
  logLevel                ERROR
  rollingSize             10M
}

accesslog /var/www/html/logs/access.log {
  useServer               0
  rollingSize             10M
  keepDays                30
  logReferer              1
  logUserAgent            1
}

index {
  useServer               0
  indexFiles              index.php, index.html, index.htm
}

scripthandler {
  add lsapi:lsphp83 php
}

extprocessor lsphp83 {
  type                    lsapi
  address                 uds://tmp/lshttpd/lsphp83.sock
  maxConns                10
  env                     PHP_LSAPI_CHILDREN=10
  env                     LSAPI_AVOID_FORK=200M
  initTimeout             600
  retryTimeout            0
  persistConn             1
  respBuffer              0
  autoStart               2
  path                    /usr/local/lsws/lsphp83/bin/lsphp
  backlog                 100
  instances               1
  priority                0
  memSoftLimit            2047M
  memHardLimit            2047M
  procSoftLimit           1400
  procHardLimit           1500
}

rewrite {
  enable                  1
  autoLoadHtaccess        1
  logLevel                0
}



context / {
  location                /var/www/html/public_html/
  allowBrowse             1
  
  rewrite {
    enable                1
    inherit               1
  }

  addDefaultCharset       off

  phpIniOverride {
    php_admin_value curl.cainfo /etc/ssl/certs/ca-certificates.crt
    php_admin_value openssl.cafile /etc/ssl/certs/ca-certificates.crt
    php_admin_value openssl.capath /etc/ssl/certs
  }
}
